### ISSUE TITLE
关于原项目

### ISSUE THREAD

**Issue by mikeyshell** [vikiboss/genshin-impact-api#1]
这两天看助手有些功能无法使用，原项目repository也没了，想请问大佬后面还维护吗

**Comment by vikiboss** [comment]
![image](https://user-images.githubusercontent.com/53367348/211156130-ec40b0ed-b18b-4f2d-a6fd-6eec9278a7cc.png)

**Comment by vikiboss** [comment]
GitHub 官方还没回复，维护是会维护的，如果实在没办法，可能考虑迁移到其他平台，比如 gitlab

**Comment by ghost** [comment]
> GitHub 官方还没回复，维护是会维护的，如果实在没办法，可能考虑迁移到其他平台，比如 gitlab

好的，看来还是加群一下
